server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: server-demo2

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000




hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    serverMethod:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#在调用serverdemo服务的时候，该服务内会模拟睡眠2秒，那么调用方的Feign和Hystrix就必须得像上边这样配置。如果Feign或者Hystrix配置的超时时间小于等于被调用
#服务的睡眠时间那么被调用服务就会降级，在调用服务中会自动进入fallback方法。上边Hystrix的这种配置方法属于全局配法，如果具体到某个方法
#需要在有@HystrixCommand(fallbackMethod = "fallback")注解的方法上再加上注解@HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds" ,value = "3000")
#这样的话它就可以覆盖全局配置的Hystrix