server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka
